### ISSUE TITLE
Language overrides for systems not working

### ISSUE THREAD

**Issue by Keiyuu** [unexpectedpanda/retool#244]
When I check the "Override global settings" box on the languages tab in system settings, it's not taken into account when processing the DAT.

I noticed that it doesn't seem to save this particular checkbox at all because when you click on the DAT in the list after changing language settings, the override box gets unchecked again. This only happens on the languages tab.

**Comment by unexpectedpanda** [comment]
Thanks for the heads up -- fixed in beta 7.

**Comment by Keiyuu** [comment]
I just noticed this bug was only partially fixed.
When trying to use an empty language list in an override it still won't save. It only works if you select at least one language.

**Comment by unexpectedpanda** [comment]
IIRC this was actually by design. It saves the override state, but if you have it enabled and no languages specified it falls back to the global order.

Given the implied language order taken from regions this isn't a great thing, so I'll modify this in beta 8.

**Comment by unexpectedpanda** [comment]
Before I change the behavior -- what were you expecting to happen with an empty list?

In my mind this should be a two-level fallback. First get the implied language order from the system region order (if enabled). If that fails, then fall back to the global language order, whether implied or specified.

**Comment by Keiyuu** [comment]
> Edit: Ah the label on the box tells you that all languages are included if a box is empty, and fairly that's probably what you were expecting. I'll fix at least that...

Yeah, that's exactly what I was trying to achieve!
I have a more refined global setting which I have as default but I change some things up for specific DATs and in this case I wanted it to consider all languages.

**Comment by unexpectedpanda** [comment]
Fixed in v2 beta 8.
